### ISSUE TITLE
NightMode - Buttons Background

### ISSUE THREAD

**Issue by luckymls** [luckymls/editor#17]
Riprodurre il bug:

**Sei in DayMode** ->Lo sfondo dei bottoni della Menubar è visibile
**Passi in Night Mode** -> Lo sfondo dei bottoni è ancora visibile
**Passi in Day Mode** -> Non è più visibile alcuno sfondo nella MenuBar

**Comment by pyThink** [comment]
Ho pronta la patch, aspetto il merge dell'ultima request e poi la carico
