### ISSUE TITLE
Bookmark- Linea 1

### ISSUE THREAD

**Issue by luckymls** [luckymls/editor#31]
![image](https://user-images.githubusercontent.com/25911479/32324568-1eea5324-bfcc-11e7-89be-41c418cceeb2.png)

ScreenShot del bug

1. Non permette di inserire segnalibri nella prima linea perchè risultano già presenti anche se vuoti, inoltre non permette l'eliminazione

**Comment by pyThink** [comment]
Quando si verifica?
