### ISSUE TITLE
Enter glitch

### ISSUE THREAD

**Issue by luckymls** [luckymls/editor#46]
Nell'editor, compare un glitch andando a capo, probabilmente legato al ridimensionamento automatico della barra laterale, il glitch si è presentato dopo aver introdotto i due pulsanti (per la scelta linguaggio e font) nella barra inferiore. Si accettano proposte

**Comment by luckymls** [comment]
Ho inoltre notato vari glitch legati alle varie opzioni proposte nel menu View (Show line number non è operativo, show infobar at the bottom causa problemi alla barra laterale e a i tasti per linguaggio e font)

**Comment by pyThink** [comment]
Avevo notato che si buggava la barra, stavo pensando di mettere i due pulsanti nel menu di sopra sotto forma di cascade

**Comment by luckymls** [comment]
Confermo, sarebbe la scelta più saggia da fare
