### ISSUE TITLE
Paste with selection bug

### ISSUE THREAD

**Issue by pyThink** [luckymls/editor#47]
Quando si incolla del testo avendone dell'altro selezionato, la selezione non viene sostituita dal testo incollato, ma rimane accanto ad esso.
Istruzioni per riprodurre:
- Selezionare del testo
- Incollare del testo mantenendo la selezione
- Non distruggere il pc

**Comment by luckymls** [comment]
Mi piace l'ultimo punto "Non distruggere il pc" hahaha
